[build]
  # Build command
  command = "npm run build"
  
  # Directory that contains the built app (Vite outputs to dist/)
  publish = "dist"
  
  # Base directory for the build
  base = "frontend"

[build.environment]
  NODE_VERSION = "18"
  # Solana Configuration - Set these in Netlify UI under Site settings > Environment variables
  # VITE_SOLANA_RPC_URL = "https://api.devnet.solana.com"
  # VITE_PROGRAM_ID = "4jGQ4kaxDsPJ57u1iN8gX1X7ngBji2Z8R8ERmcVp1BLW"
  # VITE_SOLANA_NETWORK = "devnet"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    # Add CSP to allow wallet connections
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.devnet.solana.com https://api.mainnet-beta.solana.com wss://*.solana.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

