[build]
  # Build command
  command = "npm run build"
  
  # Directory that contains the built app (Vite outputs to dist/)
  publish = "dist"
  
  # Base directory for the build
  base = "frontend"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (you'll need to set these in Netlify UI)
# [build.environment]
#   NODE_VERSION = "18"

